version: 2.1

jobs:
  build_and_test: # this can be any name you choose
    docker:
      - image: mcr.microsoft.com/playwright:v1.24.2-focal
    resource_class:
    environment:
      NODE_ENV: production
      PWDEBUG: pw:api
      DISPLAY: :99
      PORT: 4000

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Add domain.com
          command: |
            sudo tee -a /etc/hosts \<<<'127.0.0.1 ${E2E_BASE_URL}'
            cat /etc/hosts
      - run:
          name: Install Dependencies
          command: |
            Xvfb -ac :99 -screen 0 1280x1024x16 &
            yarn install --immutable --production=false
            yarn build
            yarn run playwright install --with-deps chromium
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged
      - run:
          command: |
            yarn run playwright test --config=playwright.config.ci.ts

workflows:
  tests:
    jobs:
      - build_and_test
